### ISSUE TITLE
App menu name is shortened (with ellypsis)

### ISSUE THREAD

**Issue by lfom** [hardpixel/unite-shell#166]
Hello. First, thanks for making Unite extension, it makes Gnome's top bar much more pleasant to use without all those (useless) spaces and arrows. But since I have updated to the latest version I noticed that the app menu is being shortened (please see attached imaged), what didn't happen before. It seems that it is caused by Unite because it goes back to normal if I disable it, and disabling all other (user) extensions (I am using Pop!_OS so there are some system extensions as well) does not fix the problem. I have even uninstalled and downloaded the latest version for Gnome 3.34 (v32) and still no deal. I was not able to find an Unite setting that would disable this behavior either (app menu icon/arrow don't seem to affect the shortening).

Is it a known bug? I know Gnome 3.36 was released, but maybe it affects all versions. A workaround or hotfix would be greatly appreciated.

Regards

![Screenshot from 2020-04-14 18-21-34](https://user-images.githubusercontent.com/15659999/79277401-1c10d400-7e80-11ea-9ebf-c6a3231ccc7c.png)

**Comment by jonian** [comment]
Hi @lfom, this issue is a dulicate of #144 and has been fixed. Please download the latest version of unite (v40). It is compatible with gnome-shell 3.34.

**Comment by jonian** [comment]
Duplicate of #144

**Comment by lfom** [comment]
@jonian 
Hello! I searched first, even in the closed issues, but I guess I missed #144. 

I have downloaded v40 from the Releases link, installed, logged out and rebooted, but it is still the same, please see attached screenshot.

![Screenshot from 2020-04-14 19-08-51](https://user-images.githubusercontent.com/15659999/79279145-c1797700-7e83-11ea-9993-4fc1bb78087d.png)

**Comment by jonian** [comment]
Provide screenshots with unite settings. Maybe a settings combination is causing this, or it is an issue with gnome 3.34. I'm on 3.36 and I can't test now, will need to setup a VM.

**Comment by lfom** [comment]
@jonian Thank you for your reply. Maybe it happened because I had enabled "Extend top bar left box" to see what it does? Maybe I did this a while ago, after updating it... Is there any way to reset the preferences and start over? I didn't find any file or folder with "unite" in its name besides the folder with the extension...

![Screenshot from 2020-04-14 19-30-53](https://user-images.githubusercontent.com/15659999/79280520-ea4f3b80-7e86-11ea-98c5-1a3149325cb2.png)
![Screenshot from 2020-04-14 19-31-02](https://user-images.githubusercontent.com/15659999/79280525-ecb19580-7e86-11ea-8280-a6db2c57e92e.png)

**Comment by jonian** [comment]
Settings for all extensions are handled by dconf, there is no file where the settings are saved. 

You do not need to reset the settings, I just wanted to replicate you setup to reproduce the issue. After using the same settings I can't reproduce it. 

I will need to try in a VM. What Pop!_OS version do you use?

**Comment by lfom** [comment]
Pop!_OS 19.10 / Gnome 3.34.2
unite v40

**Comment by lfom** [comment]
@jonian I have upgraded my Manjaro disk to latest versions, including Gnome 3.36.1 and I noticed that it had unite extension and it was working fine, so I copied the extension folder to my Pop!_OS 19.10 disk, disabled the extension, replaced the unite folder contents of my user with the Manjaro one, logged out and it started to work fine when I logged in again. Manajro shows the version as "-1", so I don't know what version it uses, I will attach a file with this version, maybe you can find out what's different.

[unite.tar.gz](https://github.com/hardpixel/unite-shell/files/4484252/unite.tar.gz)

**Comment by jonian** [comment]
@lfom It is version 37. Can you try with v40 replacing in `window.js`:

```js
// window.js line 178
get title() {
  if (this.showTitle) {
    return this.win.get_title()
  } else {
    return AppMenu.get_accessible_name()
  }
}

// replace with this
get title() {
  if (this.showTitle) {
    return this.win.get_title()
  } else {
    const app = AppMenu._targetApp
    return app && app.get_name()
  }
}
```

**Comment by lfom** [comment]
@jonian Yeah, doing what you said actually fixed my issue: I have disabled the extension, replaced the folder with v40, replaced the code as you said, then rebooted. The only difference that for me the code started at line 175 instead of 178 as you said, but the code that needed to be replaces was just like what you wrote.

**Comment by jonian** [comment]
Thanks for the help @lfom. Can you try the latest version from master branch, the issue should be fixed.

**Comment by lfom** [comment]
@jonian Yes, confirmed it is working fine in the current master branch (I have downloaded the master branch ZIP from GitHub, replaced the unite folder, then logged out/in again). Thanks

**Comment by jonian** [comment]
HI @lfom, I have introduced some changes in master branch that might cause a regression for this issue. Please try the master branch again. Thanks!

**Comment by lfom** [comment]
> Hi @lfom, I have introduced some changes in master branch that might cause a regression for this issue. Please try the master branch again. Thanks!

I am still on Gnome 3.34.3, just downloaded the master zip, replaced the unite folder, rebooted and it is still fine.
