### ISSUE TITLE
Top icons module support for touchscreen

### ISSUE THREAD

**Issue by jonian** [hardpixel/unite-shell#18]
Check if top icons work with touchscreen.

**Comment by jonian** [comment]
@Peetz0r can you check if the top icons work with touch screen?

https://github.com/hardpixel/unite-shell/blob/a92ce01b73a506a523c0c82ca275d84a595392c2/unite%40hardpixel.eu/modules/topIcons.js#L138

Top icons use `button-release-event`, like the window buttons did before #16.

**Comment by Peetz0r** [comment]
It's indeed broken on touch. Changing it to `clicked` causes this error on clicking:

    JS ERROR: Error: Expected type union for Argument 'event' but got type 'integer'
    TopIcons<._addTrayIcon/<@/home/peter/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/topIcons.js:139:7

But, looking on the bright side, I get the same error when touching it ;)

**Comment by jonian** [comment]
@Peetz0r thanks. Just to be sure, using `button-release-event` it does not work, correct?

**Comment by Peetz0r** [comment]
Yes, it does not work on the touchscreen.

**Comment by jonian** [comment]
@Peetz0r can you confirm that this issue is fixed?

**Comment by Peetz0r** [comment]
Nope, still broken. But the event does trigger. I added a `log('clicked event fired')` at [topIcons.js:L141](https://github.com/hardpixel/unite-shell/blob/efddac4739d1fb3f0c001e402a4db169b49267e1/unite%40hardpixel.eu/modules/topIcons.js#L141) and this is what happens on a touch:

  okt 13 00:23:27 denker gnome-shell[20891]: clicked event fired
  okt 13 00:23:27 denker gnome-shell[20891]: shell_tray_icon_click: assertion 'event_type == CLUTTER_BUTTON_RELEASE || event_type == CLUTTER_KEY_PRESS || event_type == CLUTTER_KEY_RELEASE' failed

On a normal mouse click, only the log line appears, and the program which icon I clicked raises to the top. This does not happen on touch.

**Comment by Peetz0r** [comment]
This is the point where it fails:
https://github.com/GNOME/gnome-shell/blob/master/src/shell-tray-icon.c#L200

So, it's actually a gnome bug. But maybe we can work around it and somehow fake `event_type == CLUTTER_BUTTON_RELEASE`...

**Comment by jonian** [comment]
I used the original implementation from legacy tray, as you can see here:
https://github.com/GNOME/gnome-shell/blob/3.24.0/js/ui/legacyTray.js#L140

Can you paste the log message for `log(Clutter.get_current_event())` and `log(Clutter.get_current_event().get_button())` when the icon is clicked?

>  But maybe we can work around it and somehow fake event_type == CLUTTER_BUTTON_RELEASE

This looks like the only possible solution.

BTW, thank you for your help with testing.

**Comment by Peetz0r** [comment]
Code:

    iconContainer.connect('clicked', function () {
      log('clicked event fired')
      log(Clutter.get_current_event())
      log(Clutter.get_current_event().get_button())
      icon.click(Clutter.get_current_event());
    });

On click:

    okt 13 01:09:11 denker gnome-shell[29790]: clicked event fired
    okt 13 01:09:11 denker gnome-shell[29790]: [union instance proxy GIName:Clutter.Event jsobj@0x7f1d0d387940 native@0x557e2bbd62a0]
    okt 13 01:09:11 denker gnome-shell[29790]: 1

On touch:

    okt 13 01:09:17 denker gnome-shell[29790]: clicked event fired
    okt 13 01:09:17 denker gnome-shell[29790]: [union instance proxy GIName:Clutter.Event jsobj@0x7f1d0d389130 native@0x557e2bbd6180]
    okt 13 01:09:17 denker gnome-shell[29790]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
    okt 13 01:09:17 denker gnome-shell[29790]: 0
    okt 13 01:09:17 denker gnome-shell[29790]: shell_tray_icon_click: assertion 'event_type == CLUTTER_BUTTON_RELEASE || event_type == CLUTTER_KEY_PRESS || event_type == CLUTTER_KEY_RELEASE' failed

**Comment by Peetz0r** [comment]
I also logged `Clutter.get_current_event().type()` and I got 7 (`Clutter.EventType.BUTTON_RELEASE`) on click, and I got 15 (`Clutter.EventType.TOUCH_END`) on touch.

`Clutter.get_current_event().type()` in JS seems to be the same as [`clutter_event_type()`](https://developer.gnome.org/clutter/stable/clutter-Events.html#clutter-event-type) in C. The constants are defined in [clutter-enums.h:737](https://github.com/GNOME/mutter/blob/master/clutter/clutter/clutter-enums.h#L737).

**Comment by jonian** [comment]
So theoretically the code below sjoud work:

```
iconContainer.connect('clicked', function () {
  let evt = Clutter.get_current_event();

  if (evt.type === Clutter.EventType.TOUCH_END) {
    evt.type = Clutter.EventType.BUTTON_RELEASE;
  }

  icon.click(evt);
});
```

**Comment by Peetz0r** [comment]
Nope, that does not work. `evt.type()` is a function, so you can test for it (if you add the parentheses) but not set it as a property. There is no `evt.set_type()` :(

**Comment by jonian** [comment]
According to https://stackoverflow.com/questions/34947627/how-to-create-clutter-events-with-gjs#34954527 we cannot create a Clutter.Event.

**Comment by jonian** [comment]
According to this:
https://github.com/GNOME/gnome-shell/blob/033277b68f2910e54ce62f45fa92af2f5092a7ba/src/st/st-button.c#L761

Something like the code below might work:

```
iconContainer.connect('clicked', function (actor) {
  let evt = Clutter.get_current_event();

  if (evt.type() === Clutter.EventType.TOUCH_END) {
    actor.fake_release();
  }
});

iconContainer.connect('button-release-event', function (actor, evt) {
  icon.click(evt);
});
```

**Comment by Peetz0r** [comment]
Nope :(

The code (I added a bunch of log()'s):

    iconContainer.connect('clicked', function (actor) {
      log('clicked event fired')
      let evt = Clutter.get_current_event();

      if (evt.type() === Clutter.EventType.TOUCH_END) {
        log('touch magic stuff happening')
        actor.fake_release();
      } else {
        log('no touchy')
      }
    });

    iconContainer.connect('button-release-event', function (actor, evt) {
      log('button event firing')
      icon.click(evt);
    });

On click:

    okt 13 02:50:23 denker gnome-shell[8706]: button event firing
    okt 13 02:50:23 denker gnome-shell[8706]: clicked event fired
    okt 13 02:50:23 denker gnome-shell[8706]: no touchy

On touch:

    okt 13 02:53:42 denker gnome-shell[8706]: clicked event fired
    okt 13 02:53:42 denker gnome-shell[8706]: touch magic stuff happening

This time, no failed assertions at all. But, it still works on click and nothing happens on touch.

**Comment by jonian** [comment]
I'm closing this issue since I can't find a way to fix it and the tray will be deprecated in later gnome versions.
