### ISSUE TITLE
Decorations are not removed on some SSD applications

### ISSUE THREAD

**Issue by jonian** [hardpixel/unite-shell#183]
Currently, to decide when to handle a window, unite checks the initial MOTIF_HINTS, which are in the format of `0x2, 0x0, 0x0, 0x0, 0x0`. 

If the 3rd value of the hints is different from `0x2` and `0x0`, then the window has decorations and unite handles it, as can be seen [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/window.js#L106) and [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/window.js#L73). This check is needed to avoid showing duplicate decorations on Firefox/Chrome.

Some applications, like the ones reported in #180 and #168, have hints that do not match the rule above and still have decorations. The application reported in #180 (Ensemble) has hints `0x1, 0x3e, 0x0, 0x0, 0x0`.

So there are other combinations of MOTIF_HINTS that indicate the window has decorations. The problem is, I can't find any documentation about this and help is needed to resolve the issue.

**Comment by graynk** [comment]
I sometimes get this on JetBrains products. Most of the time unite works with them correctly, but if I open a second window or restart the app then it shows decorated until I turn Unite off and on again. Is this the same issue, or is it something different?

**Comment by jonian** [comment]
Hi @graynk, sorry for the late response. Your issue might be related to this or to #173. Do you use "Auto Move Windows" extension?

**Comment by graynk** [comment]
> Hi @graynk, sorry for the late response. Your issue might be related to this or to #173. Do you use "Auto Move Windows" extension?

Yes, I do. I'll try disabling it to see if it helps, I don't use it that much anyway

**Comment by graynk** [comment]
I can confirm that disabling Auto Move Windows extension resolves the problem

**Comment by jonian** [comment]
Compatibility issue with  "Auto Move Windows" has been fixed in master branch. I will release a new version soon.

**Comment by graynk** [comment]
Issue reproduced again with "Auto Move WIndows" disabled. Again, on JetBrains products (this time PyCharm specifically). I can minimize-maximize however many times I want, but it's not removing decorations. But if I close PyCharm and then open it again, the decorations do get removed

**Comment by jonian** [comment]
When it happens again, open a terminal, type `xprop`, click the window and provide the output or only the value of `_MOTIF_WM_HINTS`. Thanks!

**Comment by graynk** [comment]
Here's the output:
`_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x1, 0x0, 0x0`

I figured out when it happens. JetBrains IDE's take some time to open. If I click on the shortcut, wait until the splash screen shows up, then focus some other window _on my second monitor_ (which does not have a top bar), then after IDE is done loading it opens up without decorations removed. If I keep focus on the main monitor, the decorations are removed

**Comment by lepa22** [comment]
The title bar is not removed on Firefox 82.0.3 on Ubuntu 20.04 too. Here is the `xprop` output:

```
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
```

**Comment by eugene-rom** [comment]
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0

Works for me. Firefox 82.0.3 on Ubuntu 20.04. _MOTIF_WM_HINTS are same.

**Comment by jonian** [comment]
@lepa22 works for me too. Try restarting Firefox. Also see https://github.com/hardpixel/unite-shell/issues/201#issuecomment-697957246

**Comment by lepa22** [comment]
@jonian Just tried that. It works. Thank you!

**Comment by eirikrrr** [comment]
Is there any workaround for the ubuntu software center?

**Comment by eduararley** [comment]
Wine decorations are not removed here, on Fedora 33 x86-54.

`_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7a, 0x0, 0x0`

**Comment by jonian** [comment]
@eduararley wine applications are recognized correctly by unite as decorated. The problem is that when you remove the decorations from a wine app they are automatically re-decorated.

You can see this by using xprop from a terminal using:

```
xprop -id wine_window_xid -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x2, 0x0, 0x0"
```

So, I don't think there is a way to undecorate wine applications.

**Comment by AI-ien** [comment]
What about Chromium based browsers? Buttons are not removed when maximized on Edge and Chromium.

**Comment by lepa22** [comment]
@AI-ien Have you tried going to your browser's _Settings_ &rarr; _Appearacne_ and select _Use system title bar and borders_?

**Comment by AI-ien** [comment]
@lepa22 yes I did. Result is the same.

**Comment by AI-ien** [comment]
@jonian, unfortunately this is happening with latest builds, for Edge version 98.0.1108.56 and Chromium version 96.0.4664.110. I will open new bug then.

**Comment by rodrigoGA** [comment]
i am using chrome 103.0.5060.114 on ubuntu 20.04 and i have double icon problem. is this problem solved?

**Comment by jonian** [comment]
@rodrigoGA the issue on chrome has been fixed, Make sure you have enabled `Use system titlebars and borders`.

**Comment by rodrigoGA** [comment]
same problem.
if I open the app called extensions from the launcher it also has the same problem (gnome tweaks display correctly
![Captura de pantalla de 2022-07-18 10-20-24](https://user-images.githubusercontent.com/2334523/179520756-9adfc243-4c3c-4e86-8c8d-2c8a3159ffe6.png)
![Captura de pantalla de 2022-07-18 10-19-54](https://user-images.githubusercontent.com/2334523/179520765-fa3977a4-2c06-4e89-b4f3-5ceaddcfb960.png)
)

**Comment by AI-ien** [comment]
> @rodrigoGA the issue on chrome has been fixed, Make sure you have enabled `Use system titlebars and borders`.

Microsoft Edge
Version 103.0.1264.62 (Official build) (64-bit)

Problem still persists.

**Comment by jonian** [comment]
Closing this as now there is a new approach on checking if a window is decorated/undecorated and if it uses client side decorations as can be seen [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/window.js#L64-L70).

Any apps that don't work with this method will be considered wont-fix.
